upload_form/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import FormView
from .forms import uploadform,uploadmodelform
from forms import LoginForm
from forms import SetForm


app_name="upload_form"

urlpatterns = [
     url(r'^$', views.index,name='index'),
     url(r'^home$', views.index, name='index'),
     url(r'^uploads/$',views.uploads, name='uploads'),
     url(r'^save/$',views.save,name='save'),
     url(r'^checkfile/$',views.checkfile,name='checkfile'),
     url(r'^downloadfile/$',views.downloadfile, name='downloadfile'),
     url(r'^deletefile/$',views.deletefile,name='deletefile'),
     url(r'^login/$','django.contrib.auth.views.login',{'authentication_form':LoginForm}),
     url(r'^logout/$','django.contrib.auth.views.logout',name = 'logout'),
     url(r'^account_activation_sent/$',views.account_activation_sent,name='account_activation_sent'),
     url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name="activate"),
     url(r'^set/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$','django.contrib.auth.views.password_reset_confirm',{'set_password_form':SetForm}),
     url(r'^reset/done/$','django.contrib.auth.views.password_reset_complete'),
]

upload_form/templates/upload_form/base.html
{% load static %}
<!DECTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FTP</title> 
  
  
<script
			  src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'upload_form/css/style.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>
<script src="{% static 'upload_form/js/dataTables.select.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'upload_form/css/select.dataTables.min.css' %}">
<script type="text/javascript"src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
<script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>

</head>
<body>
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
{% if user.is_active %}
  <a class="navbar-brand" style="color:white;">Hi {{ user.username }}{% if user.is_superuser %} / admin{% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/home">Home</a>
      {% if user.is_superuser %}
      <a class="nav-item nav-link" href="/admin">Admin</a>
      {% endif %}
      <a class="nav-item nav-link" href="/logout">Logout</a>
    </div>
  </div>
{% endif %}
</nav>
  <div class="container">
 <img id='logo' src="{% static 'upload_form/image/logo.png' %}" width="500px" alt='logo'/>

    <h2 id="title">file-uploader</h2><br>
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>  

</body>

upload_form/templates/upload_form/downloading.html
{% extends "upload_form/base.html" %} {% block content %}
<script src="{% static 'upload_form/js/downloading.js' %}"></script>
<div id="menu shadow">
  <!--<meta http-equiv="refresh" content="4;URL=/home">-->
  <div>Downloading...</div>
  <div class="progress">
    <div
      class="progress-bar progress-bar-striped bg-info progress-bar-animated"
      role="progressbar"
      style="width:0%;"
    ></div>
    <input
      type="text"
      id="filepath"
      value="{{ downloadfile }}"
      style="display:none;"
    />
    <input
      type="text"
      id="filename"
      value="{{ filename }}"
      style="display:none;"
    />
  </div>
  <input type="number" id="number" style="display:none;" value="0" />
  <div id="progress"></div>
  <br />

  <div id="box">
    <div id="progress-msg"></div>
  </div>
</div>
<a id="save"></a>
{% endblock %}

upload_form/templates/upload_form/downloads.html
{% extends "upload_form/base.html" %} {% block content %}
<script src="{% static 'upload_form/js/downloads.js' %}"></script>
<div class="menu">
  <table class="table table-hover" id="download-table">
    <thead>
      <tr>
        <th><input name="select_all" value="1" type="checkbox" /></th>
        <th>filename</th>
        <th>date</th>
        <th>description</th>
      </tr>
    </thead>
    <tbody>
      {% for value in all_data %}
      <tr class="listval">
        <td></td>
        <td>{{ value }}</td>
        <td>{{ value.timestamp }}</td>
        <td>...</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <form action="{% url 'upload_form:downloadfile' %}" method="POST">
    <div class="form-group" style="display:none;">
      <label style="float:left;" for="filename">Filename</label>
      <input
        id="filename"
        class="form-control"
        type="text"
        name="filename"
        aria-describedby="alert"
        placeholder="Filename"
        required
      />
    </div>
    <div class="col-xs-offset-2 col-xs-10 text-right">
      <small id="alert">{{ alert }}</small>
      <input
        type="submit"
        class="btn btn-primary submit"
        disabled
        value="download"
      /><br />
    </div>
    {% csrf_token %}
  </form>
  <a href="/home"
    ><i
      style="position:relative; right:10px;"
      class="fas fa-arrow-circle-left"
    ></i
    >back to home</a
  >
</div>
{% endblock %}

upload_form/templates/upload_form/index.html
{% extends "upload_form/base.html" %}
{% block content %}
{% load static %}
<script src="{% static 'upload_form/js/index.js' %}"></script>
<div class="menu">
   <table class="table table-hover" id="download-table">
      <thead>
         <tr>
            <th></th>
            <th>filename</th>
            <th>date</th>
            <th>size</th>
            <th>description</th>
{% if request.user.is_superuser %}
            <th>user</th>
{% endif %}
         </tr>
      </thead>
      <tbody>
{% for value in all_data %}
         <tr class="listval">
            <td></td>
            <td>{{ value.filename }}</td>
            <td>{{ value.timestamp }}</td>
            <td>{{ value.size }}</td>
            <td>{{ value.description }}</td>
{% if request.user.is_superuser %}
            <td>{{ value.user }}</td>
{% endif %}
         </tr>
{% endfor %}
      </tbody>
      <medium id="alert">{{ alert }}</medium>
   </table>
   <form action="{% url 'upload_form:downloadfile' %}" method="POST">
      <div class="form-group" style="display:none;">
         <label style="float:left;" for="filename">Filename</label>
         <input id="filename" class="form-control" type="text" name="filename" aria-describedby="alert" placeholder="Filename" required>
{% if request.user.is_superuser %}
         <input id="username" type="text" name="name" required>
{% endif %}
      </div>
      <div class="col-xs-offset-2 col-xs-10 text-right">
         <div id="buttons">
            <div class="btn btn-upload btn-outline-primary upload">upload</a></div>
            <input type="submit"  class="btn btn-outline-secondary submit disabled" value="download">
            <div class="btn btn-outline-danger delete disabled" data-toggle="modal" data-target="#deletemodal" onclick="deletelist()" >delete</div>
         </div>
      </div>
{% csrf_token %}
   </form>
</div>

<!-- MODAL -->
<div class="modal fade" id="deletemodal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
     <div class="modal-body">
     </div>
 <form action="{% url 'upload_form:deletefile' %}" method="POST">
     <input class="delete" type="text" name="deletefile" style="display:none;" required>
     {% if request.user.is_superuser %}
     <input class="user" type="text" name="username" style="display:none;" required>
     {% endif %}
     <div class="modal-footer" style="display:flex;">
         <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
         <input type="submit" class="btn btn-outline-danger" value="delete"/>
     </div>
     {% csrf_token %}
     </form>
    </div>
  </div>
</div>
{% endblock %}

upload_form/templates/upload_form/upload.html
{% extends "upload_form/base.html" %}
{% block content %}
<script src="{% static 'upload_form/js/upload.js' %}"></script>

<div class="menu">
<div class="uploadform">
  <form id="form" enctype="multipart/form-data" action="/save" method="post">
  	{% csrf_token %}
  	{{ form.filename }}
        <label for="{{ uploadfile.name }}">Uploadfile</label>
        {{ form.uploadfile }}
        <label for="{{ description.auto_id }}">Description</label>
        {{ form.description }}
        {{ form.size }}
        <div id="alert">{{ alert }}</div><br>
  	<input id="file" class="btn btn-outline-primary" type="button" value="upload">
  </form>
</div>
<div class="progress"> <div class="progress-bar progress-bar-striped bg-info progress-bar-animated" role="progressbar" style="width:0%;"></div>
</div>
<div id="progress"></div>
<div id="progress-msg"></div>
</div>

<!-- MODAL -->
<div class="modal  fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true" ">
  <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-body">
     <div id="complete">Upload completed.</div>
     </div>
     <div class="modal-footer" style="display:flex;">
         <button type="button" id="uploadmore" class="btn btn-outline-primary" >Upload more</button>
         <button type="button" id="home" class="btn btn-outline-info" value="delete">Home</button>
     </div>
 </div>
</div>
</div>
{% endblock %}